application: citizen-journalist
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images
- url: /styles
  static_dir: styles
- url: /bower_components
  static_dir: bower_components
- url: /.*
  script: mainpage.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest
  
